# Two pods, one container each
# Each container asking for 1 distinct tpu

---
apiVersion: v1
kind: Namespace
metadata:
  name: tpu-test

---
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  namespace: tpu-test
  name: all-tpus
spec:
  spec:
    devices:
      requests:
      - name: tpus
        exactly:
          deviceClassName: tpu.google.com
          allocationMode: All

---
apiVersion: v1
kind: Pod
metadata:
  namespace: tpu-test
  name: tpu-pod0
  labels:
    app: pod
spec:
  tolerations:
  - key: "google.com/tpu"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: ctr0
    image: busybox:latest
    command:
        - /bin/sh
        - -c
        - |
          echo "Environment Variables:"
          env
          echo "Listing v4 mounts"
          ls /dev/ | grep 'accel'
          echo "Listing v5+ mounts"
          ls /dev/vfio
          echo "Listing log mounts:"
          ls /tmp
          echo "Sleeping indefinitely..."
          sleep infinity
    resources:
      claims:
      - name: tpu
  resourceClaims:
  - name: tpu
    resourceClaimTemplateName: all-tpus
